steps:
  - label: ":hammer: Tests"
    plugins:
      - docker#v3.9.0:
          image: ubuntu
          env:
            - MY_USER = "JohnDoe"
            - MY_PASSWORD = "Welcome@123"
    command: echo $MY_USER $MY_PASSWORD
