steps:
  - label: ":hammer: Tests"
    plugins:
      - docker#v3.9.0:
          image: ubuntu
          environment:
            - USER = "JohnDoe"
            - PASSWORD = "Welcome@123"
    command: echo $USER $PASSWORD
             env | grep -E "USER|PASSWORD"
