steps:
  - label: ":hammer: Tests"
    command: echo $USER $PASSWORD
    plugins:
      - docker#v3.9.0:
          image: ubuntu
          user: root
          env:
            - USER : "JohnDoe"
            - PASSWORD : "Welcome@123"
