steps:
  - label: ":hammer: Tests"
    plugins:
      - docker#v3.9.0:
          image: ubuntu
          user: root
          env:
            - USER
            - PASSWORD
    command: echo $USER $PASSWORD
