steps:
  - label: ":hammer: Tests"
    command: echo $USER $PASSWORD
    plugins:
      - docker#v3.5.0:
          image: ubuntu
          user: root
          env:
            - USER
            - PASSWORD
